version: '3.9'

volumes:
  caddy_data:
  caddy_config:

services:


  server:
    build: ./server
    working_dir: /go/src/github.com/MohammadBnei/gRPC-web-tuto/server
    platform: linux/amd64
    environment:
      - GODEBUG=http2debug=1
    ports:
      - 4000:4000
    volumes:
      - ./server:/go/src/github.com/MohammadBnei/gRPC-web-tuto/server
      - ./proto/go/todoPB:/go/src/github.com/MohammadBnei/gRPC-web-tuto/server/todoPB
      - ./dev/certs:/cert
    command: gowatch
    stdin_open: true
  
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: grpctodo

  grpc-file:
    build: 
      dockerfile: DockerfileGrpc
    volumes:
      - ./proto:/gen/proto
      - ./proto/go:/out/go
      - ./proto/js:/out/js
      - ./Makefile:/Makefile
    # command: bash -c "protoc -I /gen/proto \
    #               --go_out=plugins=grpc,paths=source_relative:/go \
    #               --js_out=import_style=commonjs,binary:/js \
    #               --grpc-web_out=import_style=typescript,mode=grpcweb:/js \
    #               /gen/proto/todo.proto"
    stdin_open: true

  envoy:
    image: envoyproxy/envoy:v1.22.0
    volumes:
      - ./dev/envoy.yml:/etc/envoy/envoy.yml
      - ./dev/certs/grpctodo.dev-key.pem:/etc/certs/key.pem
      - ./dev/certs/grpctodo.dev.pem:/etc/certs/cert.pem
    ports: 
      - 8081:8081
      - 9901:9901
    stdin_open: true
    command: envoy -c /etc/envoy/envoy.yml -l trace