version: '3.9'

services:
  server:
    build:
      dockerfile: ./server/Dockerfile
      # We set the context to the base direcotry to inject the certificates and the proto files
      context: ./
    # For mac m1 users only
    # platform: linux/amd64
    volumes:
      - ./dev/certs/grpctodo.dev+1-key.pem:/certs/key.pem:ro
      - ./dev/certs/grpctodo.dev+1.pem:/certs/cert.pem:ro
      - ./server:/go/src/github.com/MohammadBnei/grpctodo/server
      - ./proto/go/todoPB:/go/src/github.com/MohammadBnei/grpctodo/server/todoPB:ro
    command: gowatch

  front:
      image: node:16
      working_dir: /app
      volumes:
      - ./dev/certs/grpctodo.dev+1-key.pem:/certs/key.pem:ro
      - ./dev/certs/grpctodo.dev+1.pem:/certs/cert.pem:ro
      - ./svelte:/app/
      - ./proto/js:/app/src/proto
      command: npm run dev

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: grpctodo

  envoy:
    image: envoyproxy/envoy:v1.22.0
    volumes:
      - ./dev/envoy.yml:/etc/envoy/envoy.yml
      - ./dev/certs/grpctodo.dev+1-key.pem:/etc/certs/key.pem:ro
      - ./dev/certs/grpctodo.dev+1.pem:/etc/certs/cert.pem:ro
    ports:
      - 443:8081
      - 9901:9901
    command: envoy -c /etc/envoy/envoy.yml