serverConfig:
  tlsEnabled: true
  port: "4000"
  certPath: "/certs/cert.pem"
  keyPath: "/certs/key.pem"
postgres:
  username: "postgres"
  password: "postgres"
  endpoint: "postgres"
  port: "5432"
  dBName: "grpctodo"