serverConfig:
  tlsEnabled: true
  port: "4000"
  certPath: "/cert/grpctodo.dev.pem"
  keyPath: "/cert/grpctodo.dev-key.pem"
postgres:
  username: "postgres"
  password: "postgres"
  endpoint: "postgres"
  port: "5432"
  dBName: "grpctodo"